[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "md-pdf"
version = "0.1.0"
description = "Markdown to PDF converter"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hatchling>=1.27.0",
    "markdown>=3.7",
    "weasyprint>=65.1",
]
